### PR TITLE
Add password recovery method (i.e. recover forgot password), add config directory

### PR DESCRIPTION
**Pull request by CristianCantoro**
As per subject, the following PR adds a "forgot password" view for resetting password, with link via email.

I have added support for config file (in `project/config.py`), the files are stored in the `project/config` directory.

C

### CODE REVIEW

**Comment by mjhea0** [comment]
Thanks! Can you update the failing tests?

**Comment by CristianCantoro** [comment]
Hi @mjhea0, I have corrected the test and I have added new one (all my test pass), there are two minor problems:
- the Travis build fails because there is no `APP_SETTINGS` environment variable set, how am I supposed to set that on the testing server?
- the url for resetting the password after having received the ling `/forgot/new/<token>` gives me a 404 error if I put in an invalid token, I don't understand why it is not routing the request correctly.

**Comment by mjhea0** [comment]
The environment variable is set. The `APP_SETTINGS` issue is with the testing config. I can debug the token issue after you get the `APP_SETTINGS` updated. Thanks!

**Comment by CristianCantoro** [comment]
Hi,

I am evidently missing something. The [Travis build](https://travis-ci.org/realpython/flask-registration/builds/155100440) gives the following:

```
$ python manage.py test
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    from project import app, db
  File "/home/travis/build/realpython/flask-registration/project/__init__.py", line 24, in <module>
    app.config.from_object(os.environ['APP_SETTINGS'])
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'APP_SETTINGS'
```

That error is raised by [L24](https://github.com/realpython/flask-registration/blob/master/project/__init__.py#L24) in `__init__.py` which is a file not touched by this PR. That operation is executed before anything I could have modified is called or executed, at least as far as I know.

I have (locally) the same error if I do not set `APP_SETTINGS`, and I have the same error if I use the code from your master branch (i. e. https://github.com/realpython/flask-registration/commit/db371d6134c4ac93c8b86795c4575c9fd3dd6f7a)

Furthermore, the `KeyError` means that the env variable `APP_SETTINGS` is not present in the dictionary, i.e. that the env variable is not set.

What am I missing?

**Comment by mjhea0** [comment]
Strange. I set the env variables in the travis env. Can you update the travis.yml file? https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-.travis.yml

**Comment by CristianCantoro** [comment]
Hi,

I keep having problems with the build system. I have simplified the pull request and I have eliminated the code for reading from the configuration files (maybe I will make a separated pull request). The only things that I have modified in `config.py` is the fact that now you can read the values for `MAIL_SERVER`, `MAIL_PORT`, `MAIL_USE_TLS` and `MAIL_USE_SSL` from environment variables, but the defaults are the same as the old values.

In `config.py` at [L26-L27](https://github.com/realpython/flask-registration/blob/master/project/config.py#L26-L27) the two env vars `APP_MAIL_USERNAME` and `APP_MAIL_PASSWORD` are read, with no fallback on default values if they are not defined. In this case, if they are not set an exception will be thrown. Now, this is exactly what is happening with the latest [Travis build](https://travis-ci.org/realpython/flask-registration/jobs/155385288) that is complaining that `APP_MAIL_USERNAME` and `APP_MAIL_PASSWORD` are not set.

I don't know why these settings are not applied, maybe they depend on who is pushing the changes? I do not want to put any credentials in `.travis.yml` which is publicly viewable.

C

**Comment by mjhea0** [comment]
Add the dummy keys to travis.yml => https://travis-ci.org/realpython/flask-registration/builds/155523258

**Comment by mjhea0** [comment]
Good!

Next, you do NOT want to actually send emails in testing mode (and you may not want to send them in dev mode either). How do you want to handle this? You could just output the email to the console or you could set up a fake smtp server?

https://www.google.com/search?safe=off&q=python+testing+mail+server+mock&oq=python+testing+mail+server+mock&gs_l=serp.3...1001.1001.0.1363.1.1.0.0.0.0.125.125.0j1.1.0....0...1c.1.64.serp..0.0.0.ikw63FPJ3lM

**Comment by CristianCantoro** [comment]
Hi,

I have finally wrapped my head around the build system.

First, you can see that when you launched the build yourself with the code from my branch (see [build #39](https://travis-ci.org/realpython/flask-registration/jobs/155523259)) the environment variables were correctly set at the beginning (and then overwritten by the dummy ones), while when I was pushing changes to the pull request the subsequent build does not do to initial set up (see [build #46](https://travis-ci.org/realpython/flask-registration/jobs/155596488)). 

This behavior is designed purposefully by Travis. The documentation pages about [environment variables](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) and [pull requests and security sestrictions](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions) say respectively:

> By default, the value of these new environment variables [set in the repository settings] is hidden from the export line in the logs. This corresponds to the behavior of encrypted variables in your .travis.yml.
> 
> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.
> 
> [source](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)

and 

> The most important restriction for pull requests is about secure environment variables and encrypted data.
> 
> A pull request sent from a fork of the upstream repository could be manipulated to expose any environment variables. The upstream repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone with a fork.
> 
> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.
> 
> Pull requests sent from forked repositories do not have access to encrypted variables or data.
> 
> [source](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions)

So, I have created my own account on Travis-CI and I have set all the needed environment variables with my SMTP server settings and login. The build [completed successfully](https://travis-ci.org/CristianCantoro/flask-registration/builds/155596480). So, I have eliminated the dummy variables from the `.travis.yml` file that you set in [build #39](https://travis-ci.org/realpython/flask-registration/jobs/155523259) because they were causing a login error on my SMTP server (this is to be expected).

The errors in [build #39](https://travis-ci.org/realpython/flask-registration/jobs/155523259) - both `AttributeError: 'AnonymousUserMixin' object has no attribute 'confirmed'` were caused by yet another weird setting. When the variable `TESTING` is set to `True` Flask-login automatically disables the login decorators ([source](http://stackoverflow.com/questions/21765210/disabling-login-required-while-unit-testing-flask-with-flask-login)). I have set (in `config.py` [L62](https://github.com/CristianCantoro/flask-registration/blob/master/project/config.py#L62)) the variable `LOGIN_DISABLED=False` because I suppose that otherwise the tests about login redirection make no sense.

Finally, I have written a `CONTRIBUTING.md` file with a detailed explanation on how to set up a local development environment and a testing environment on Travis. Hope this helps.

**Comment by CristianCantoro** [comment]
About emails, I have been using [Mailgun](https://mailgun.com/) sandbox domain for development and testing. It actually sends email when in development mode, no email is sent when in testing mode, if I am not mistaken.

Anyhow, I have found that there are several solution instead of setting up a local mocking SMTP (how would you set it up automatically in Travis, then?), for example I have found:
- [Debug Mail](https://debugmail.io/projects)
- [Mailtrap](https://mailtrap.io/)
- [MailCatcher](https://mailcatcher.me/) (this needs to be self-hosted)

I am trying Debug Mail and it seems very convenient and easy to set up and use.

**Comment by mjhea0** [comment]
👍

**Comment by mjhea0** [comment]
So, at this point, I need to remove the env variables from travis.yml, sign up for debug mail, and then set the env variables for debug mail login?

**Comment by CristianCantoro** [comment]
Hi @mjhea0, yes!

As you can see, in [my build](https://travis-ci.org/CristianCantoro/flask-registration/jobs/155671898) I have set up the following env vars (i.e. [Travis repository settings](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)):

``` bash
$ export APP_SETTINGS=project.config.TestingConfig
$ export APP_MAIL_SERVER=debugmail.io
$ export APP_MAIL_PORT=25
$ export APP_MAIL_USE_TLS=true
$ export APP_MAIL_USE_SSL=false
$ export APP_MAIL_USERNAME=[secure]
$ export APP_MAIL_PASSWORD=[secure]
```

You may want to change the defaults in `config.py` (lines [#L39-L42](Lhttps://github.com/CristianCantoro/flask-registration/blob/master/project/config.py#L39-L42) to Debug Mail) if you like.

At that point, if you launch the build on my branch, all test should pass.

**Comment by mjhea0** [comment]
Sweet! 👍

**Comment by mjhea0** [comment]
If you ever want some paid work, email us -> info at realpython dot com

**Pull request merged**
